name: Daily Portfolio Email

on:
  schedule:
    # Run every hour between 16:00–21:00 UTC; the script will self-decide whether to send.
    - cron: '0 * * * 1-5'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dateutil

      - name: Run daily wrap (America/Chicago logic inside the script)
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
          TZ: America/Chicago
        run: |
          python "daily_wrap.py"
