name: Daily Portfolio Email

on:
  schedule:
    # Weekdays, every hour (GitHub cron is UTC). Script will send once per session.
    - cron: "0 * * * 1-5"
  workflow_dispatch: {}

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dateutil

      - name: Run daily wrap
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
          TZ: America/Chicago
        run: |
          # optional: tag subject so you can spot GH emails easily
          sed -i 's/subject = f"/subject = f"[GH] /' daily_wrap.py || true
          python daily_wrap.py | tee run.log

      - name: Upload CSV artifact (if produced)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-csv
          path: |
            **/portfolio_daily_*.csv
          if-no-files-found: ignore

      - name: Post run summary
        if: always()
        run: |
          echo "## Daily Wrap Run" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Time (UTC):** $(date -u '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tail of log:**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          tail -n 40 run.log | sed 's/$/  /' >> $GITHUB_STEP_SUMMARY
